apiVersion: v2
name: mlops-platform
description: A Helm chart for deploying MLOps platform components
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: airflow
    version: 8.8.0
    repository: https://airflow.apache.org/
    condition: airflow.enabled
    
  - name: mlflow
    version: 0.7.5
    repository: https://community-charts.github.io/helm-charts
    condition: mlflow.enabled
    
  - name: prometheus
    version: 23.1.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    
  - name: grafana
    version: 6.59.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
    
  - name: istio-base
    version: 1.18.1
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
    
  - name: istiod
    version: 1.18.1
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
    
  - name: istio-ingress
    version: 1.18.1
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
    
  - name: kfserving
    version: 0.5.1
    repository: https://storage.googleapis.com/kfserving-charts
    condition: kfserving.enabled

maintainers:
  - name: MLOps Team
    email: mlops@example.com
